"""init

Revision ID: ef084b2f1d45
Revises: 
Create Date: 2026-03-19 04:42:32.025695
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef084b2f1d45'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eval_configs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dimension_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deterministic_weight', sa.Float(), nullable=False),
    sa.Column('llm_weight', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('evaluations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('jd_id', sa.String(length=32), nullable=False),
    sa.Column('resume_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'parsing', 'scoring_deterministic', 'scoring_llm', 'fusing', 'completed', 'failed', name='eval_status'), nullable=False),
    sa.Column('deterministic_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('tier', sa.String(length=5), nullable=False),
    sa.Column('meta_summary', sa.Text(), nullable=False),
    sa.Column('interview_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jd_id', 'resume_id', name='uix_jd_resume')
    )
    op.create_index(op.f('ix_evaluations_jd_id'), 'evaluations', ['jd_id'], unique=False)
    op.create_index(op.f('ix_evaluations_resume_id'), 'evaluations', ['resume_id'], unique=False)
    op.create_table('job_descriptions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('parsed_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_descriptions_cache_key'), 'job_descriptions', ['cache_key'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('candidate_name', sa.String(length=500), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('parsed_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_file_hash'), 'resumes', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumes_file_hash'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_job_descriptions_cache_key'), table_name='job_descriptions')
    op.drop_table('job_descriptions')
    op.drop_index(op.f('ix_evaluations_resume_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_jd_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_table('eval_configs')
    # ### end Alembic commands ###
